id: A9535C25A
base_file: fF079.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:48:09.132941
  last_modified_at: 2022-06-15 20:48:09.132946
