id: A9535C25A
base_file: f6366.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:48:09.130937
  last_modified_at: 2022-06-15 20:48:09.130945
